server:
  port: 8010
spring:
  application:
    name: springboot-security-jwt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    password: root
    username: root


redis:
  password: root
  database: 0
  address: localhost
  port: 6379


jwt:
  secret: zheshiyigexiangmyuzhongdemiyaonizhidaolealdahwhdr
  expire-time-in-second: 1209600
  header: token
  path: /login
